[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arize-phoenix[evals]>=11.36.0",
    "huggingface-hub[hf-xet]>=0.35.1",
    "llama-index>=0.14.2",
    "llama-index-callbacks-arize-phoenix>=0.6.1",
    "llama-index-embeddings-azure-openai>=0.4.1",
    "llama-index-embeddings-huggingface>=0.6.1",
    "llama-index-llms-azure-openai>=0.4.1",
    "llama-index-llms-ollama>=0.7.3",
    "llama-index-vector-stores-chroma>=0.5.3",
    "matplotlib>=3.10.6",
    "openinference-instrumentation-llama-index>=4.3.5",
    "opentelemetry-exporter-otlp>=1.37.0",
    "opentelemetry-proto>=1.37.0",
    "opentelemetry-sdk>=1.37.0",
    "pytest>=8.4.2",
    "pyyaml>=6.0.2",
    "seaborn>=0.13.2",
]
